"""Generate seed data JSON for all 12 products."""
import json, os

P = [
    ("Capers","Câpres","كبار","Alcaparras","Capperi","capers","capers",True,[1,2,3],
     "Premium hand-picked Moroccan capers, sorted by calibre.",
     "Câpres marocaines triées par calibre, cueillies à la main.",
     "كبار مغربي مقطوف يدوياً ومصنف حسب الحجم.",
     "Alcaparras marroquíes seleccionadas a mano, clasificadas por calibre.",
     "Capperi marocchini raccolti a mano, selezionati per calibro.",
     "Hand-picked Moroccan capers sorted by calibre. Available in brine, vinegar, or dry salt.",
     "Câpres marocaines cueillies à la main, triées par calibre. En saumure, vinaigre ou sel sec.",
     "كبار مغربي مقطوف يدوياً ومصنف حسب الحجم. متوفر في محلول ملحي أو خل أو ملح جاف.",
     "Alcaparras marroquíes seleccionadas a mano. Disponibles en salmuera, vinagre o sal seca.",
     "Capperi marocchini raccolti a mano. Disponibili in salamoia, aceto o sale secco.",
     ["En saumure","En vinaigre","En sel sec"],"products/capers.png"),
    ("Caperberries","Câprons","ثمار الكبار","Alcaparrones","Frutti di cappero","caperberries","capers",True,[1,2],
     "Moroccan caperberries with stems, mild olive-like flavour.",
     "Câprons marocains à la saveur douce ressemblant à l'olive.",
     "ثمار الكبار المغربية بنكهة خفيفة تشبه الزيتون.",
     "Alcaparrones marroquíes con tallos, sabor suave similar a la aceituna.",
     "Frutti di cappero marocchini con gambo, sapore delicato simile all'oliva.",
     "Caperberries with stems, ideal for tapas, cocktails, and gourmet garnishes.",
     "Câprons avec tiges, idéals pour les tapas, cocktails et garnitures.",
     "ثمار الكبار بالسيقان، مثالية للمقبلات والكوكتيلات.",
     "Alcaparrones con tallos, ideales para tapas, cócteles y guarniciones.",
     "Frutti di cappero con gambo, ideali per tapas, cocktail e guarnizioni.",
     ["En saumure","En vinaigre"],"products/caperberries.png"),
    ("Hot Peppers","Les piments","الفلفل الحار","Pimientos picantes","Peperoncini","hot-peppers","peppers",False,[1,2],
     "Assorted hot peppers preserved in brine or vinegar.",
     "Assortiment de piments conservés en saumure ou vinaigre.",
     "تشكيلة فلفل حار محفوظ في المحلول الملحي أو الخل.",
     "Surtido de pimientos picantes conservados en salmuera o vinagre.",
     "Assortimento di peperoncini conservati in salamoia o aceto.",
     "A variety of hot peppers, preserved to retain their natural heat and flavour.",
     "Une variété de piments, conservés pour garder leur chaleur et saveur naturelles.",
     "تشكيلة من الفلفل الحار المحفوظ للحفاظ على حرارته ونكهته.",
     "Variedad de pimientos picantes conservados para mantener su sabor natural.",
     "Varietà di peperoncini conservati per mantenere il loro sapore naturale.",
     ["En saumure","En vinaigre"],"products/hot-peppers.png"),
    ("Piri Piri","Piri Piri","بيري بيري","Piri Piri","Piri Piri","piri-piri","peppers",True,[1,2],
     "Small, fiery Piri-Piri peppers packed in vinegar.",
     "Petits piments Piri-Piri ardents conservés dans le vinaigre.",
     "فلفل بيري بيري صغير وحار محفوظ في الخل.",
     "Pequeños pimientos Piri-Piri ardientes conservados en vinagre.",
     "Piccoli peperoncini Piri-Piri conservati in aceto.",
     "Fiery Piri-Piri peppers, a staple in African and Portuguese cuisines.",
     "Piments Piri-Piri ardents, un incontournable de la cuisine africaine et portugaise.",
     "فلفل بيري بيري الحار، عنصر أساسي في المطبخ الأفريقي والبرتغالي.",
     "Pimientos Piri-Piri, un básico de la cocina africana y portuguesa.",
     "Peperoncini Piri-Piri, un elemento essenziale della cucina africana e portoghese.",
     ["En saumure","En vinaigre"],"products/piri-piri.png"),
    ("Piparra","Piparra","بيبارا","Piparra","Piparra","piparra","peppers",False,[1,2],
     "Mild Basque peppers, tangy and crisp.",
     "Piments basques doux, acidulés et croquants.",
     "فلفل الباسك الخفيف، حامض ومقرمش.",
     "Pimientos vascos suaves, ácidos y crujientes.",
     "Peperoni baschi delicati, aciduli e croccanti.",
     "Pickled Basque peppers, mild and tangy — a tapas essential.",
     "Piments basques marinés, doux et acidulés, essentiels pour les tapas.",
     "فلفل الباسك المخلل، خفيف وحامض — أساسي للمقبلات.",
     "Pimientos vascos encurtidos, suaves y ácidos — esenciales para tapas.",
     "Peperoni baschi sottaceto, delicati e aciduli — essenziali per le tapas.",
     ["En vinaigre"],"products/piparra.png"),
    ("Guindilla","Guindilla","غيندبلا","Guindilla","Guindilla","guindilla","peppers",False,[1,2],
     "Spanish Guindilla peppers, mildly spicy.",
     "Piments Guindilla espagnols, légèrement épicés.",
     "فلفل غيندبلا الإسباني، معتدل الحرارة.",
     "Pimientos Guindilla españoles, ligeramente picantes.",
     "Peperoni Guindilla spagnoli, leggermente piccanti.",
     "Mildly spicy Guindilla peppers, perfect with pintxos and grilled dishes.",
     "Piments Guindilla légèrement épicés, parfaits avec les pintxos et grillades.",
     "فلفل غيندبلا معتدل الحرارة، مثالي مع البينتشوس والمشويات.",
     "Pimientos Guindilla ligeramente picantes, perfectos con pintxos y parrilladas.",
     "Peperoni Guindilla leggermente piccanti, perfetti con pintxos e grigliate.",
     ["En vinaigre"],"products/guindilla.png"),
    ("Cut Red/Yellow/Green Peppers","Piment rouge/jaune/vert coupé","فلفل أحمر/أصفر/أخضر مقطع",
     "Pimiento rojo/amarillo/verde cortado","Peperoni rossi/gialli/verdi tagliati","cut-peppers","peppers",False,[1,2],
     "Tri-colour cut peppers preserved in brine or vinegar.",
     "Piments tricolores coupés, conservés en saumure ou vinaigre.",
     "فلفل مقطع ثلاثي الألوان محفوظ في محلول ملحي أو خل.",
     "Pimientos tricolor cortados, conservados en salmuera o vinagre.",
     "Peperoni tricolore tagliati, conservati in salamoia o aceto.",
     "Pre-cut red, yellow, and green peppers, ready for industrial and food-service use.",
     "Piments pré-coupés, prêts pour l'industrie et la restauration.",
     "فلفل أحمر وأصفر وأخضر مقطع مسبقاً، جاهز للاستخدام الصناعي.",
     "Pimientos precortados, listos para uso industrial y de restauración.",
     "Peperoni pre-tagliati, pronti per uso industriale e ristorazione.",
     ["En saumure","En vinaigre"],""),
    ("Harissa","Harissa","هريسة","Harissa","Harissa","harissa","peppers",True,[1,2],
     "Authentic North-African hot chili paste.",
     "Pâte de piment fort nord-africaine authentique.",
     "معجون الفلفل الحار الأصيل من شمال أفريقيا.",
     "Pasta de chile picante norteafricana auténtica.",
     "Pasta di peperoncino nordafricana autentica.",
     "Traditional harissa paste, a versatile condiment for marinades, couscous, and grills.",
     "Pâte de harissa traditionnelle, condiment polyvalent pour marinades, couscous et grillades.",
     "معجون الهريسة التقليدي، توابل متعددة الاستخدامات للتتبيلات والكسكس والمشويات.",
     "Pasta de harissa tradicional, condimento versátil para adobos, cuscús y parrillas.",
     "Pasta di harissa tradizionale, condimento versatile per marinature, couscous e grigliate.",
     [],""),
    ("Preserved Lemons","Citron confit","ليمون مخلل","Limones en conserva","Limoni conservati","preserved-lemons","pickles",True,[1,2],
     "Salt-preserved lemons, essential for Moroccan tagines.",
     "Citrons confits au sel, essentiels pour les tajines marocains.",
     "ليمون مخلل بالملح، أساسي للطاجين المغربي.",
     "Limones conservados en sal, esenciales para los tagines marroquíes.",
     "Limoni conservati sotto sale, essenziali per i tajine marocchini.",
     "Whole lemons cured in salt, a cornerstone of Moroccan and Mediterranean cooking.",
     "Citrons entiers confits au sel, un pilier de la cuisine marocaine et méditerranéenne.",
     "ليمون كامل مخلل بالملح، ركيزة المطبخ المغربي والمتوسطي.",
     "Limones enteros curados en sal, pilar de la cocina marroquí y mediterránea.",
     "Limoni interi sotto sale, pilastro della cucina marocchina e mediterranea.",
     ["En saumure","En sel sec"],""),
    ("Pearl / Silver / Silverskin Onions","Oignon pearl / silver","بصل لؤلؤي / فضي",
     "Cebollitas perla / plateadas","Cipolline argentate","pearl-silver-onions","pickles",False,[1,2],
     "Small pickled onions, crisp and tangy.",
     "Petits oignons marinés, croquants et acidulés.",
     "بصل صغير مخلل، مقرمش وحامض.",
     "Cebollitas encurtidas, crujientes y ácidas.",
     "Cipolline sottaceto, croccanti e acidule.",
     "Pearl and silverskin onions, pickled for charcuterie boards, salads, and garnishes.",
     "Oignons grelots marinés pour planches de charcuterie, salades et garnitures.",
     "بصل لؤلؤي مخلل للسلطات والمقبلات والتزيين.",
     "Cebollitas en vinagre para tablas, ensaladas y guarniciones.",
     "Cipolline sottaceto per taglieri, insalate e guarnizioni.",
     ["En vinaigre"],""),
    ("Lampascioni","Lampascioni","لمباسكيوني","Lampascioni","Lampascioni","lampascioni","pickles",False,[1],
     "Pickled Mediterranean wild onions for antipasto.",
     "Oignons sauvages méditerranéens marinés pour antipasti.",
     "بصل بري متوسطي مخلل للمقبلات.",
     "Cebollas silvestres mediterráneas encurtidas para antipasto.",
     "Cipolle selvatiche mediterranee sottaceto per antipasto.",
     "Wild Mediterranean onion bulbs, pickled in vinegar. A southern-Italian delicacy.",
     "Bulbes d'oignons sauvages, marinés au vinaigre. Délicatesse du sud de l'Italie.",
     "بصل بري متوسطي مخلل في الخل. طبق إيطالي جنوبي شهي.",
     "Bulbos de cebolla silvestre en vinagre. Delicia del sur de Italia.",
     "Bulbi di cipolla selvatica sottaceto. Prelibatezza del sud Italia.",
     ["En vinaigre"],""),
    ("Cornichons","Cornichons","كورنيشون","Pepinillos","Cetriolini","cornichons","pickles",False,[1,2],
     "French-style gherkins, crisp and tart.",
     "Cornichons à la française, croquants et acidulés.",
     "كورنيشون فرنسي، مقرمش وحامض.",
     "Pepinillos estilo francés, crujientes y ácidos.",
     "Cetriolini alla francese, croccanti e aciduli.",
     "Classic French-style cornichons, the ideal accompaniment for pâtés and charcuterie.",
     "Cornichons classiques à la française, accompagnement idéal pour pâtés et charcuterie.",
     "كورنيشون كلاسيكي فرنسي، المرافق المثالي للباتيه واللحوم الباردة.",
     "Pepinillos clásicos franceses, acompañamiento ideal para patés y embutidos.",
     "Cetriolini classici alla francese, accompagnamento ideale per paté e salumi.",
     ["En vinaigre"],""),
]

GRADES = ["A","B","C","D","E"]

data = []
for p in P:
    (ne,nf,na,ns,ni,slug,cat,feat,cals,
     se,sf,sa,ss,si,de,df,da,ds,di,pres,img) = p
    data.append({
        "name_en":ne,"name_fr":nf,"name_ar":na,"name_es":ns,"name_it":ni,
        "slug":slug,"category":cat,"is_featured":feat,
        "calibers":cals,"grades":GRADES,
        "short_en":se,"short_fr":sf,"short_ar":sa,"short_es":ss,"short_it":si,
        "desc_en":de,"desc_fr":df,"desc_ar":da,"desc_es":ds,"desc_it":di,
        "preservations":pres,"image":img,
        "shelf_life":"36 months","storage":"Cool dry place, 5-25°C","origin":"Morocco",
    })

out = os.path.join(os.path.dirname(__file__),"core","fixtures","products.json")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out,"w",encoding="utf-8") as f:
    json.dump(data,f,ensure_ascii=False,indent=2)
print(f"Wrote {len(data)} products to {out}")
