import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'capersmed.settings')
django.setup()

from core.models import Product

def populate():
    print("Clearing old products...")
    Product.objects.all().delete()
    
    products_data = [
        {
            "name_en": "Preserved Lemons",
            "name_fr": "Citrons Confits au Sel",
            "name_ar": "الحامض المصر",
            "category": "pickles",
            "is_premium": False,
            "short_description_en": "Authentic Moroccan preserved lemons - a staple ingredient in traditional tagines and North African cuisine.",
            "short_description_fr": "Authentiques citrons confits marocains - un ingrédient de base pour les tajines traditionnels et la cuisine nord-africaine.",
            "short_description_ar": "حامض مصير مغربي أصيل - مكون أساسي في الطواجن التقليدية ومطبخ شمال أفريقيا.",
            "description_en": "Our Citrons Confits are prepared using a traditional Moroccan method passed down through generations. Whole lemons are preserved in salt and their own juices, creating a unique flavor that's both tangy and mellow. Essential for authentic Moroccan cooking, these preserved lemons add depth and complexity to tagines, couscous, salads, and marinades.",
            "description_fr": "Nos Citrons Confits sont préparés selon une méthode marocaine traditionnelle transmise de génération en génération. Les citrons entiers sont conservés dans le sel et leur propre jus, créant une saveur unique à la fois acidulée et douce. Indispensables pour la cuisine marocaine authentique.",
            "description_ar": "يتم تحضير الحامض المصير لدينا باستخدام طريقة مغربية تقليدية. يتم حفظ الليمون الكامل في الملح وعصيره الخاص، مما يخلق نكهة فريدة لاذعة ومعتدلة في نفس الوقت. ضروري للطبخ المغربي الأصيل.",
            "features_en": ["Traditional Moroccan preservation method", "100% natural - no artificial preservatives", "Essential for authentic tagines", "Whole lemons preserved in salt"],
            "features_fr": ["Méthode traditionnelle de conservation marocaine", "100% naturel - sans conservateurs artificiels", "Indispensable pour les tajines authentiques", "Citrons entiers conservés dans le sel"],
            "features_ar": ["طريقة حفظ مغربية تقليدية", "طبيعي 100٪ - خالي من المواد الحافظة", "ضروري للطواجن الأصيلة", "حامض كامل محفوظ في الملح"],
            "uses_en": ["Traditional Moroccan tagines", "Couscous dishes", "Salad dressings", "Fish and chicken marinades", "Mediterranean recipes"],
            "uses_fr": ["Tajines marocains traditionnels", "Plats de couscous", "Vinaigrettes", "Marinades pour poissons et poulets", "Recettes méditerranéennes"],
            "uses_ar": ["طواجن مغربية تقليدية", "أطباق الكسكس", "تتبيلات السلطة", "تتبيلات السمك والدجاج", "وصفات البحر الأبيض المتوسط"],
            "specifications_en": {"Packaging": "Glass jar, 720g net weight", "Origin": "Morocco", "Quality": "Qualité Supérieure (Superior Quality)"},
            "specifications_fr": {"Emballage": "Bocal en verre, 720g poids net", "Origine": "Maroc", "Qualité": "Qualité Supérieure"},
            "specifications_ar": {"التعبئة": "وعاء زجاجي، وزن صافي 720 جم", "المنشأ": "المغرب", "الجودة": "جودة عالية"},
            "is_featured": True
        },
        {
            "name_en": "Caperberries",
            "name_fr": "Câprons en Conserve",
            "name_ar": "ثمار الكبار المحفوظة",
            "category": "pickles",
            "is_premium": False,
            "short_description_en": "Premium caperberries with stems - a gourmet delicacy perfect for charcuterie boards and Mediterranean dishes.",
            "short_description_fr": "Câprons premium avec tiges - une délicatesse gastronomique parfaite pour les planches de charcuterie et les plats méditerranéens.",
            "short_description_ar": "ثمار كبار فاخرة بأعوادها - طعام شهي ومثالي لأطباق اللحوم الباردة وأطباق البحر الأبيض المتوسط.",
            "description_en": "Our Câprons are hand-selected caperberries preserved at peak freshness. Unlike capers, these are the mature fruit of the caper bush, offering a milder, more delicate flavor. Each berry is carefully preserved with its elegant stem intact, making them perfect for upscale presentations and gourmet dishes.",
            "description_fr": "Nos Câprons sont sélectionnés à la main et conservés à une fraîcheur optimale. Contrairement aux câpres, il s'agit du fruit mûr du câprier, offrant une saveur plus douce et plus délicate. Chaque baie est soigneusement conservée avec sa tige élégante.",
            "description_ar": "يتم اختيار ثمار الكبار المحفوظة لدينا بعناية ويتم حفظها في ذروة نضارتها. على عكس الكبار، هذه هي الفاكهة الناضجة لشجيرة الكبار، وتوفر نكهة أخف وأكثر دقة.",
            "features_en": ["Whole berries with decorative stems", "Hand-picked at optimal ripeness", "Mild, delicate Mediterranean flavor", "Perfect for elegant presentations"],
            "features_fr": ["Baies entières avec tiges décoratives", "Cueillies à la main à maturité optimale", "Saveur méditerranéenne douce et délicate", "Parfait pour des présentations élégantes"],
            "features_ar": ["ثمار كاملة مع سيقان زخرفية", "منتقاة يدويًا عند النضج الأمثل", "نكهة متوسطية خفيفة وحساسة", "مثالية للتقديم الأنيق"],
            "uses_en": ["Charcuterie and cheese boards", "Cocktail garnishes", "Tapas and antipasti platters", "Gourmet salads", "Mediterranean appetizers"],
            "uses_fr": ["Planches de charcuterie et fromages", "Garnitures de cocktails", "Plateaux de tapas et antipasti", "Salades gourmandes", "Apéritifs méditerranéens"],
            "uses_ar": ["ألواح اللحوم الباردة والجبن", "زينة الكوكتيل", "أطباق المقبلات", "سلطات فاخرة", "مقبلات متوسطية"],
            "specifications_en": {"Packaging": "Glass jar, 720g net weight", "Origin": "Morocco", "Quality": "Qualité Supérieure (Superior Quality)"},
            "specifications_fr": {"Emballage": "Bocal en verre, 720g poids net", "Origine": "Maroc", "Qualité": "Qualité Supérieure"},
            "specifications_ar": {"التعبئة": "وعاء زجاجي، وزن صافي 720 جم", "المنشأ": "المغرب", "الجودة": "جودة عالية"},
            "is_featured": True
        },
        {
            "name_en": "Moroccan Caperberries",
            "name_fr": "Câpreberries du Maroc",
            "name_ar": "ثمار الكبار المغربية",
            "category": "pickles",
            "is_premium": True,
            "short_description_en": "Artisanal Moroccan caperberries with an elegant gold-embossed label - our premium gourmet selection.",
            "short_description_fr": "Câprons marocains artisanaux avec une élégante étiquette dorée en relief - notre sélection gastronomique premium.",
            "short_description_ar": "ثمار كبار مغربية يدوية الصنع مع ملصق ذهبي أنيق - اختيارنا الفاخر الذواقة.",
            "description_en": "Our premium Câpreberries du Maroc represent the finest selection from Moroccan caper harvests. Each berry is hand-selected for size, quality, and flavor. Preserved using time-honored techniques, these caperberries offer a sophisticated taste experience with their delicate brine and subtle Mediterranean notes.",
            "description_fr": "Nos Câpreberries du Maroc haut de gamme représentent la meilleure sélection des récoltes marocaines. Chaque baie est sélectionnée à la main pour sa taille, sa qualité et sa saveur. Conservées grâce à des techniques ancestrales.",
            "description_ar": "تمثل ثمار كبار المغرب الفاخرة لدينا أفضل اختيار من محصول الكبار المغربي. يتم اختيار كل حبة يدوياً للحجم والجودة والنكهة. محفوظة باستخدام تقنيات عريقة.",
            "features_en": ["Premium hand-selected caperberries", "Traditional Moroccan preservation", "Elegant presentation with decorative stems", "Gourmet quality for fine dining"],
            "features_fr": ["Câprons premium sélectionnés à la main", "Conservation marocaine traditionnelle", "Présentation élégante avec tiges décoratives", "Qualité gastronomique pour la haute cuisine"],
            "features_ar": ["ثمار كبار فاخرة منتقاة يدويا", "حفظ مغربي تقليدي", "تقديم أنيق مع سيقان زخرفية", "جودة ذواقة للطعام الفاخر"],
            "uses_en": ["Fine dining presentations", "Upscale cocktail garnishes", "Gourmet cheese pairings", "Mediterranean fusion cuisine", "Premium gift baskets"],
            "uses_fr": ["Présentations de haute cuisine", "Garnitures de cocktails haut de gamme", "Accords fromages gourmands", "Cuisine fusion méditerranéenne", "Paniers cadeaux premium"],
            "uses_ar": ["عروض الطعام الفاخرة", "زينة الكوكتيل الراقية", "أزواج الجبن الفاخرة", "طبخ البحر الأبيض المتوسط المدمج", "سلال هدايا فاخرة"],
            "specifications_en": {"Packaging": "Premium glass jar with ornate gold label", "Origin": "Morocco", "Grade": "Premium Gourmet Selection"},
            "specifications_fr": {"Emballage": "Bocal en verre premium avec étiquette dorée", "Origine": "Maroc", "Qualité": "Sélection Gastronomique Premium"},
            "specifications_ar": {"التعبئة": "وعاء زجاجي فاخر بملصق ذهبي مزخرف", "المنشأ": "المغرب", "الجودة": "اختيار الذواقة الفاخر"},
            "is_featured": True
        },
        {
            "name_en": "Cornichons (French Gherkins)",
            "name_fr": "Cornichons",
            "name_ar": "الخيار المخلل",
            "category": "pickles",
            "is_premium": False,
            "short_description_en": "Crispy, tangy French-style cornichons - the perfect accompaniment to charcuterie, pâtés, and sandwiches.",
            "short_description_fr": "Cornichons croquants et acidulés à la française - l'accompagnement parfait pour la charcuterie, les pâtés et les sandwichs.",
            "short_description_ar": "خيار مخلل مقرمش على الطريقة الفرنسية - المرافق المثالي للحوم الباردة والفطائر والسندويشات.",
            "description_en": "Our Cornichons are small, crisp gherkins pickled in the traditional French style with a perfectly balanced vinegar brine, aromatic herbs, and spices. These crunchy delicacies offer the ideal contrast to rich meats and cheeses, making them an essential component of any charcuterie board.",
            "description_fr": "Nos Cornichons sont de petits concombres croquants marinés dans le style traditionnel français avec une saumure au vinaigre parfaitement équilibrée, des herbes aromatiques et des épices. Ces délices croquants offrent le contraste idéal avec les viandes et les fromages riches.",
            "description_ar": "الخيار المخلل لدينا عبارة عن خيار صغير ومقرمش مخلل بالطريقة الفرنسية التقليدية مع محلول ملحي متوازن تمامًا من الخل والأعشاب العطرية والتوابل. توفر هذه الأطباق الشهية المقرمشة تبايناً مثالياً مع اللحوم الغنية والأجبان.",
            "features_en": ["Traditional French recipe", "Extra crunchy texture", "Tangy, aromatic flavor", "Perfect pickle-to-bite ratio"],
            "features_fr": ["Recette traditionnelle française", "Texture extra croquante", "Saveur acidulée et aromatique", "Proportion parfaite pickle-bouchée"],
            "features_ar": ["وصفة فرنسية تقليدية", "ملمس مقرمش إضافي", "نكهة لاذعة وعطرية", "نسبة مثالية لكل قضمة"],
            "uses_en": ["Charcuterie and pâté accompaniment", "French sandwiches (jambon-beurre)", "Raclette and fondue", "Burger and sandwich toppings", "Tartar sauce ingredient"],
            "uses_fr": ["Accompagnement de charcuterie et pâté", "Sandwichs français (jambon-beurre)", "Raclette et fondue", "Garnitures de hamburgers et sandwichs", "Ingrédient de sauce tartare"],
            "uses_ar": ["مرافق اللحوم الباردة والفطائر", "السندويشات الفرنسية", "راكليت وفوندو", "إضافات البرجر والسندويشات", "مكون لصلصة التارتار"],
            "specifications_en": {"Packaging": "Glass jar with decorative label", "Origin": "Morocco", "Style": "French Traditional"},
            "specifications_fr": {"Emballage": "Bocal en verre avec étiquette décorative", "Origine": "Maroc", "Style": "Traditionnel Français"},
            "specifications_ar": {"التعبئة": "وعاء زجاجي بملصق مزخرف", "المنشأ": "المغرب", "الأسلوب": "فرنسي تقليدي"},
            "is_featured": False
        },
        {
            "name_en": "Piri-Piri Peppers",
            "name_fr": "Piment Piri-Piri",
            "name_ar": "فلفل بيري بيري",
            "category": "spicy",
            "is_premium": False,
            "short_description_en": "Fiery piri-piri peppers preserved in vinegar - bring authentic African heat to any dish.",
            "short_description_fr": "Piments piri-piri fougueux conservés dans le vinaigre - apportez la chaleur africaine authentique à n'importe quel plat.",
            "short_description_ar": "فلفل بيري بيري حار محفوظ في الخل - يضفي حرارة أفريقية أصلية على أي طبق.",
            "description_en": "Our Piri-Piri peppers are small but mighty, offering an intense heat balanced with fruity, tangy notes. Preserved whole in aromatic vinegar, these peppers are a staple in Portuguese and African cuisine. Use them to add authentic spice to marinades, sauces, or simply as a zesty condiment.",
            "description_fr": "Nos piments Piri-Piri sont petits mais puissants, offrant une chaleur intense équilibrée par des notes fruitées et acidulées. Conservés entiers dans un vinaigre aromatique, ces piments sont un incontournable de la cuisine portugaise et africaine.",
            "description_ar": "فلفل بيري بيري لدينا صغير ولكنه قوي، يقدم حرارة شديدة متوازنة مع روائح فواكه لاذعة. محفوظة كاملة في خل عطري، وهي عنصر أساسي في المطبخ البرتغالي والأفريقي.",
            "features_en": ["Authentic African hot peppers", "Preserved whole in vinegar", "Intense heat with fruity undertones", "Versatile culinary ingredient"],
            "features_fr": ["Piments africains authentiques", "Conservés entiers dans le vinaigre", "Chaleur intense avec des notes fruitées", "Ingrédient culinaire polyvalent"],
            "features_ar": ["فلفل حار أفريقي أصيل", "محفوظ كامل في الخل", "حرارة شديدة مع مسحة فواكه", "مكون للطهي متعدد الاستخدامات"],
            "uses_en": ["Piri-piri sauce base", "Marinades for chicken and seafood", "Pizza and pasta topping", "Hot sauce recipes", "Spicy vinegar infusions"],
            "uses_fr": ["Base de sauce piri-piri", "Marinades pour poulet et fruits de mer", "Garniture de pizza et pâtes", "Recettes de sauces piquantes", "Infusions de vinaigre épicé"],
            "uses_ar": ["قاعدة صلصة بيري بيري", "تتبيلات الدجاج والمأكولات البحرية", "إضافات البيتزا والمعكرونة", "وصفات الصلصة الحارة", "منقوع الخل الحار"],
            "specifications_en": {"Heat Level": "🌶️🌶️🌶️ (Medium-Hot)", "Packaging": "Glass jar", "Origin": "Morocco"},
            "specifications_fr": {"Niveau de piquant": "🌶️🌶️🌶️ (Moyen-Fort)", "Emballage": "Bocal en verre", "Origine": "Maroc"},
            "specifications_ar": {"مستوى الحرارة": "🌶️🌶️🌶️ (متوسط-حار)", "التعبئة": "وعاء زجاجي", "المنشأ": "المغرب"},
            "is_featured": True
        },
        {
            "name_en": "Moroccan Harissa",
            "name_fr": "Harissa du Maroc",
            "name_ar": "هريسة المغرب",
            "category": "spicy",
            "is_premium": True,
            "short_description_en": "Authentic Moroccan harissa paste - a bold blend of chilies, spices, and aromatic herbs.",
            "short_description_fr": "Pâte de harissa marocaine authentique - un mélange audacieux de piments, d'épices et d'herbes aromatiques.",
            "short_description_ar": "هريسة مغربية أصلية - مزيج جريء من الفلفل الحار والبهارات والأعشاب العطرية.",
            "description_en": "Our Harissa du Maroc is crafted using a traditional recipe that balances fiery red chilies with cumin, coriander, garlic, and aromatic spices. This versatile paste is the heart of North African cuisine, adding depth, heat, and complex flavor to countless dishes. Made with premium ingredients and authentic Moroccan methods.",
            "description_fr": "Notre Harissa du Maroc est élaborée selon une recette traditionnelle qui équilibre les piments rouges ardents avec le cumin, la coriandre, l'ail et les épices aromatiques. Cette pâte polyvalente est le cœur de la cuisine nord-africaine.",
            "description_ar": "تم إعداد هريسة المغرب لدينا باستخدام وصفة تقليدية توازن الفلفل الأحمر الحار مع الكمون والكزبرة والثوم والبهارات العطرية. هذا المعجون المتعدد الاستخدامات هو قلب مطبخ شمال أفريقيا.",
            "features_en": ["Traditional Moroccan recipe", "Bold, complex spice blend", "Perfect balance of heat and flavor", "Premium quality ingredients"],
            "features_fr": ["Recette traditionnelle marocaine", "Mélange d'épices audacieux et complexe", "Équilibre parfait entre chaleur et saveur", "Ingrédients de qualité supérieure"],
            "features_ar": ["وصفة مغربية تقليدية", "مزيج توابل جريء ومعقد", "توازن مثالي بين الحرارة والنكهة", "مكونات عالية الجودة"],
            "uses_en": ["Tagines and couscous", "Marinades for meat and fish", "Soups and stews", "Sandwich spread", "Dip base with olive oil"],
            "uses_fr": ["Tajines et couscous", "Marinades pour viande et poisson", "Soupes et ragoûts", "Pâte à tartiner pour sandwich", "Base de trempette avec de l'huile d'olive"],
            "uses_ar": ["الطواجن والكسكس", "تتبيلات اللحوم والأسماك", "الشوربات واليخنات", "دهن السندويشات", "قاعدة تغميس مع زيت الزيتون"],
            "specifications_en": {"Heat Level": "🌶️🌶️🌶️ (Medium-Hot)", "Packaging": "Premium glass jar with ornate label", "Origin": "Morocco", "Style": "Traditional Moroccan"},
            "specifications_fr": {"Niveau de piquant": "🌶️🌶️🌶️ (Moyen-Fort)", "Emballage": "Bocal en verre premium avec étiquette ornée", "Origine": "Maroc", "Style": "Marocain Traditionnel"},
            "specifications_ar": {"مستوى الحرارة": "🌶️🌶️🌶️ (متوسط-حار)", "التعبئة": "وعاء زجاجي فاخر بملصق مزخرف", "المنشأ": "المغرب", "الأسلوب": "مغربي تقليدي"},
            "is_featured": True
        },
        {
            "name_en": "Piparra Peppers",
            "name_fr": "Piments Piparra",
            "name_ar": "فلفل البيبارا",
            "category": "pickles",
            "is_premium": False,
            "short_description_en": "Sweet and tangy Basque-style green peppers - mild, flavorful, and perfect for tapas.",
            "short_description_fr": "Piments verts doux et acidulés de style basque - légers, savoureux et parfaits pour les tapas.",
            "short_description_ar": "فلفل أخضر حلو ولاذع على طريقة إقليم الباسك - خفيف، لذيذ ومثالي لأطباق التاباس.",
            "description_en": "Our Piparra peppers are a Basque delicacy - slender green peppers with a sweet, mild flavor and slight tangy finish. Unlike spicy peppers, piparras offer gentle heat and crisp texture, making them ideal for those who enjoy pepper flavor without overwhelming spice. A staple in Spanish tapas culture.",
            "description_fr": "Nos piments Piparra sont une délicatesse basque - de fins piments verts avec une saveur douce et légère et une finale légèrement acidulée. Contrairement aux piments forts, les piparras offrent une chaleur douce et une texture croquante.",
            "description_ar": "فلفل البيبارا لدينا هو طعام شهي من إقليم الباسك - فلفل أخضر رفيع بنكهة حلوة ومعتدلة ونهاية لاذعة قليلا. يوفر حرارة لطيفة وملمس مقرمش.",
            "features_en": ["Mild, sweet Basque peppers", "Traditional Spanish recipe", "Crisp, tender texture", "No overwhelming heat"],
            "features_fr": ["Piments basques doux et légers", "Recette traditionnelle espagnole", "Texture croquante et tendre", "Pas de chaleur excessive"],
            "features_ar": ["فلفل باسك خفيف وحلو", "وصفة إسبانية تقليدية", "ملمس مقرمش وطري", "لا توجد حرارة مفرطة"],
            "uses_en": ["Spanish tapas platters", "Pintxos (Basque appetizers)", "Salad ingredient", "Sandwich and burger topping", "Side dish for grilled meats"],
            "uses_fr": ["Plateaux de tapas espagnols", "Pintxos (apéritifs basques)", "Ingrédient de salade", "Garniture pour sandwichs et hamburgers", "Accompagnement de viandes grillées"],
            "uses_ar": ["أطباق تاباس إسبانية", "مقبلات إقليم الباسك", "مكونات سلطة", "إضافات السندويشات والبرجر", "طبق جانبي للحوم المشوية"],
            "specifications_en": {"Heat Level": "🌶️ (Mild)", "Packaging": "Glass jar", "Origin": "Morocco", "Style": "Basque Traditional"},
            "specifications_fr": {"Niveau de piquant": "🌶️ (Doux)", "Emballage": "Bocal en verre", "Origine": "Maroc", "Style": "Traditionnel Basque"},
            "specifications_ar": {"مستوى الحرارة": "🌶️ (خفيف)", "التعبئة": "وعاء زجاجي", "المنشأ": "المغرب", "الأسلوب": "باسك تقليدي"},
            "is_featured": False
        },
        {
            "name_en": "Lampascioni",
            "name_fr": "Lampascioni",
            "name_ar": "لامباشيوني المغرب",
            "category": "pickles",
            "is_premium": True,
            "short_description_en": "Artisanal pickled lampascioni bulbs - a rare Mediterranean delicacy with unique sweet-bitter flavor.",
            "short_description_fr": "Bulbes de lampascioni marinés artisanaux - un mets méditerranéen rare à la saveur douce-amère unique.",
            "short_description_ar": "بصيلات لامباشيوني مخللة يدوية الصنع - طعام متوسطي نادر بنكهة حلوة ومرة فريدة من نوعها.",
            "description_en": "Lampascioni are wild onion bulbs prized in Italian and Mediterranean cuisine for their distinctive flavor profile - slightly bitter, pleasantly sweet, and uniquely aromatic. Our lampascioni are carefully harvested and preserved with pearl onions, aromatic herbs, and spices, creating a gourmet antipasto ingredient that's both traditional and sophisticated.",
            "description_fr": "Les Lampascioni sont des bulbes d'oignons sauvages très prisés dans la cuisine italienne et méditerranéenne pour leur profil aromatique distinctif - légèrement amer, agréablement doux et uniquement aromatique. Nos lampascioni sont soigneusement récoltés et conservés.",
            "description_ar": "لامباشيوني هي بصيلات بصل بري تحظى بتقدير كبير في المطبخ الإيطالي والبحر الأبيض المتوسط بسبب نكهتها المميزة - مرة قليلاً، حلوة بشكل مبهج، وعطرية بشكل فريد. يتم حصاد لامباشيوني لدينا بعناية وحفظها.",
            "features_en": ["Rare Mediterranean specialty", "Unique sweet-bitter flavor", "Traditional Italian preservation", "Gourmet quality selection"],
            "features_fr": ["Spécialité méditerranéenne rare", "Saveur douce-amère unique", "Conservation italienne traditionnelle", "Sélection de qualité gourmande"],
            "features_ar": ["تخصص متوسطي نادر", "نكهة حلوة ومرة فريدة", "حفظ إيطالي تقليدي", "اختيار جودة الذواقة"],
            "uses_en": ["Italian antipasto platters", "Mediterranean salads", "Pasta and rice dishes", "Gourmet pizza topping", "Artisanal food pairings"],
            "uses_fr": ["Plateaux antipasti italiens", "Salades méditerranéennes", "Plats de pâtes et de riz", "Garniture de pizza gourmande", "Accords de produits artisanaux"],
            "uses_ar": ["أطباق مقبلات إيطالية", "سلطات البحر الأبيض المتوسط", "أطباق المكرونة والأرز", "تزيين البيتزا الفاخرة", "أزواج طعام يدوية الصنع"],
            "specifications_en": {"Packaging": "Premium glass jar with ornate label", "Origin": "Morocco", "Style": "Italian Traditional"},
            "specifications_fr": {"Emballage": "Bocal en verre premium avec étiquette ornée", "Origine": "Maroc", "Style": "Traditionnel Italien"},
            "specifications_ar": {"التعبئة": "وعاء زجاجي فاخر بملصق مزخرف", "المنشأ": "المغرب", "الأسلوب": "إيطالي تقليدي"},
            "is_featured": False
        },
        {
            "name_en": "Apple Cider Vinegar",
            "name_fr": "Vinaigre de Cidre",
            "name_ar": "خل التفاح",
            "category": "vinegars",
            "is_premium": False,
            "short_description_en": "100% natural apple cider vinegar - crafted for culinary excellence and wellness.",
            "short_description_fr": "Vinaigre de cidre de pomme 100% naturel - conçu pour l'excellence culinaire et le bien-être.",
            "short_description_ar": "خل تفاح طبيعي 100٪ - مصمم للتميز في الطهي والعافية.",
            "description_en": "Our Vinaigre de Cidre is produced through natural fermentation of premium apples, resulting in a rich, smooth vinegar with complex fruity notes. Unpasteurized and unfiltered, it retains beneficial enzymes and nutrients. Perfect for both gourmet cooking and as a healthful addition to your daily routine.",
            "description_fr": "Notre Vinaigre de Cidre est produit par fermentation naturelle de pommes de première qualité, ce qui donne un vinaigre riche et doux avec des notes fruitées complexes. Non pasteurisé et non filtré, il conserve ses enzymes et nutriments bénéfiques.",
            "description_ar": "يتم إنتاج خل التفاح لدينا من خلال التخمير الطبيعي للتفاح الفاخر، مما ينتج عنه خل غني وسلس مع نغمات فواكه معقدة. غير مبستر وغير مصفى، فهو يحتفظ بالإنزيمات والعناصر الغذائية المفيدة.",
            "features_en": ["100% natural fermentation", "Made from premium apples", "Rich, smooth flavor profile", "Culinary and wellness uses"],
            "features_fr": ["Fermentation 100% naturelle", "Fabriqué à partir de pommes de première qualité", "Profil de saveur riche et doux", "Usages culinaires et bien-être"],
            "features_ar": ["تخمير طبيعي 100٪", "مصنوع من تفاح فاخر", "نكهة غنية وسلسة", "استخدامات للطهي والعافية"],
            "uses_en": ["Salad dressings and vinaigrettes", "Marinades for meat and fish", "Pickling and preserving", "Health tonic (diluted with water)", "Cooking and deglazing"],
            "uses_fr": ["Sauces à salade et vinaigrettes", "Marinades pour viande et poisson", "Décapage et conservation", "Tonique santé (dilué avec de l'eau)", "Cuisson et déglaçage"],
            "uses_ar": ["تتبيلات السلطة", "تتبيلات اللحوم والأسماك", "التخليل والحفظ", "منشط صحي (مخفف بالماء)", "الطبخ وفك الطلاء"],
            "specifications_en": {"Packaging": "Glass bottle, 500ml", "Origin": "Morocco", "Type": "Natural Fermented"},
            "specifications_fr": {"Emballage": "Bouteille en verre, 500ml", "Origine": "Maroc", "Type": "Fermenté Naturellement"},
            "specifications_ar": {"التعبئة": "زجاجة زجاجية، 500 مل", "المنشأ": "المغرب", "النوع": "مخمر طبيعيا"},
            "is_featured": True
        },
        {
            "name_en": "Red Wine Vinegar",
            "name_fr": "Vinaigre de Vin Rouge",
            "name_ar": "خل النبيذ أحمر",
            "category": "vinegars",
            "is_premium": False,
            "short_description_en": "Traditional red wine vinegar - aged for optimal depth and gourmet flavor.",
            "short_description_fr": "Vinaigre de vin rouge traditionnel - vieilli pour une profondeur optimale et une saveur gastronomique.",
            "short_description_ar": "خل نبيذ أحمر تقليدي - معتق للحصول على عمق أمثل ونكهة ذواقة.",
            "description_en": "Our Vinaigre de Vin Rouge is crafted from quality red wine and aged to develop its rich, complex character. With a perfect balance of acidity and subtle wine notes, this vinegar elevates everything from simple salads to sophisticated sauces. A staple in French and Mediterranean kitchens.",
            "description_fr": "Notre Vinaigre de Vin Rouge est élaboré à partir de vin rouge de qualité et vieilli pour développer son caractère riche et complexe. Avec un équilibre parfait d'acidité et de subtiles notes de vin.",
            "description_ar": "يتم إعداد خل النبيذ الأحمر لدينا من النبيذ الأحمر عالي الجودة ومعتق لتطوير طابعه الغني والمعقد. بتوازن مثالي بين الحموضة ورائحة النبيذ الخفية.",
            "features_en": ["Aged for optimal flavor", "Deep, complex taste", "Perfect acidity balance", "Traditional wine vinegar production"],
            "features_fr": ["Vieilli pour une saveur optimale", "Goût profond et complexe", "Équilibre d'acidité parfait", "Production traditionnelle de vinaigre de vin"],
            "features_ar": ["معتق للحصول على نكهة مثالية", "طعم عميق ومعقد", "توازن مثالي في الحموضة", "إنتاج تقليدي لخل النبيذ"],
            "uses_en": ["Classic vinaigrettes", "Reduction sauces", "Braising and deglazing", "Marinating red meats", "Gourmet cooking"],
            "uses_fr": ["Vinaigrettes classiques", "Sauces de réduction", "Braisage et déglaçage", "Marinade de viandes rouges", "Cuisine gastronomique"],
            "uses_ar": ["تتبيلات كلاسيكية", "صلصات التقليل", "الطهي ببطء وفك الطلاء", "تتبيل اللحوم الحمراء", "طبخ الذواقة"],
            "specifications_en": {"Packaging": "Glass bottle with decorative label, 500ml", "Origin": "Morocco", "Type": "Aged Wine Vinegar"},
            "specifications_fr": {"Emballage": "Bouteille en verre avec étiquette décorative, 500ml", "Origine": "Maroc", "Type": "Vinaigre de Vin Vieilli"},
            "specifications_ar": {"التعبئة": "زجاجة بملصق مزخرف، 500 مل", "المنشأ": "المغرب", "النوع": "خل نبيذ معتق"},
            "is_featured": False
        },
        {
            "name_en": "White Wine Vinegar",
            "name_fr": "Vinaigre de Vin Blanc",
            "name_ar": "خل النبيذ أبيض",
            "category": "vinegars",
            "is_premium": False,
            "short_description_en": "Light and versatile white wine vinegar - perfect for delicate dishes and bright flavors.",
            "short_description_fr": "Vinaigre de vin blanc léger et polyvalent - parfait pour les plats délicats et les saveurs vives.",
            "short_description_ar": "خل نبيذ أبيض خفيف ومتعدد الاستخدامات - مثالي للأطباق الرقيقة والنكهات الزاهية.",
            "description_en": "Our Vinaigre de Vin Blanc offers a clean, crisp acidity with subtle fruity notes from premium white wine. Its lighter flavor profile makes it ideal for dishes where you want vinegar's brightness without overpowering other ingredients. Essential for classic French cuisine and modern cooking alike.",
            "description_fr": "Notre Vinaigre de Vin Blanc offre une acidité nette et vive avec de subtiles notes fruitées de vin blanc de qualité supérieure. Son profil de saveur plus léger le rend idéal pour les plats où vous recherchez la brillance du vinaigre sans masquer les autres ingrédients.",
            "description_ar": "يوفر خل النبيذ الأبيض لدينا حموضة نظيفة وهشة مع نغمات فواكه خفية من النبيذ الأبيض الفاخر. المظهر الجانبي لنكهته الأخف يجعله مثاليًا للأطباق التي تريد فيها سطوع الخل دون التغلب على المكونات الأخرى.",
            "features_en": ["Light, crisp acidity", "Delicate white wine notes", "Versatile culinary use", "Premium quality production"],
            "features_fr": ["Acidité légère et vive", "Notes délicates de vin blanc", "Utilisation culinaire polyvalente", "Production de qualité supérieure"],
            "features_ar": ["حموضة خفيفة وهشة", "ملاحظات نبيذ أبيض حساسة", "استخدامات للطهي متعددة الاستخدامات", "إنتاج عالي الجودة"],
            "uses_en": ["Béarnaise and beurre blanc sauces", "Seafood and fish dishes", "Light vinaigrettes", "Pickling vegetables", "Hollandaise reduction"],
            "uses_fr": ["Sauces béarnaise et beurre blanc", "Plats de fruits de mer et poissons", "Vinaigrettes légères", "Marinade de légumes", "Réduction hollandaise"],
            "uses_ar": ["صلصات هولندية وبيرنيز", "أطباق المأكولات البحرية والأسماك", "تتبيلات خفيفة", "تخليل الخضروات", "تخفيضات هولندية"],
            "specifications_en": {"Packaging": "Glass bottle, 500ml", "Origin": "Morocco", "Type": "White Wine Vinegar"},
            "specifications_fr": {"Emballage": "Bouteille en verre, 500ml", "Origine": "Maroc", "Type": "Vinaigre de Vin Blanc"},
            "specifications_ar": {"التعبئة": "زجاجة، 500 مل", "المنشأ": "المغرب", "النوع": "خل نبيذ أبيض"},
            "is_featured": False
        },
        {
            "name_en": "Moroccan Capers",
            "name_fr": "Câpres du Maroc",
            "name_ar": "كبر المغرب",
            "category": "pickles",
            "is_premium": True,
            "short_description_en": "Premium hand-picked Moroccan capers - the finest quality for Mediterranean cuisine.",
            "short_description_fr": "Câpres marocaines cueillies à la main de qualité supérieure - la meilleure qualité pour la cuisine méditerranéenne.",
            "short_description_ar": "نبات الكبر المغربي المنتقى يدويًا الممتاز - أجود جودة لمأكولات البحر الأبيض المتوسط.",
            "description_en": "Our Câpres du Maroc are harvested from wild caper bushes in Morocco's sun-drenched landscapes. Hand-picked at the perfect size and preserved in traditional brine, these capers deliver the intense, tangy-salty flavor that's essential to Mediterranean cooking. Their firm texture and bold taste elevate everything from pasta to fish dishes.",
            "description_fr": "Nos Câpres du Maroc sont récoltées sur des câpriers sauvages dans les paysages ensoleillés du Maroc. Cueillies à la main à la taille parfaite et conservées dans une saumure traditionnelle, ces câpres offrent la saveur intense et acidulée-salée essentielle à la cuisine méditerranéenne.",
            "description_ar": "يتم حصاد الكبر المغربي من شجيرات الكبر البرية في المناظر الطبيعية المشمسة في المغرب. يتم اختيارها يدويًا بالحجم المثالي وحفظها في محلول ملحي تقليدي، توفر هذه الكبر النكهة القوية واللاذعة والمالحة التي تعتبر ضرورية لطبخ البحر الأبيض المتوسط.",
            "features_en": ["Hand-picked wild Moroccan capers", "Premium size selection", "Traditional brine preservation", "Rich Mediterranean flavor"],
            "features_fr": ["Câpres sauvages marocaines cueillies à la main", "Sélection de taille premium", "Conservation traditionnelle en saumure", "Riche saveur méditerranéenne"],
            "features_ar": ["كبر مغربي بري منتقى يدويا", "اختيار حجم ممتاز", "حفظ محلول ملحي تقليدي", "نكهة متوسطية غنية"],
            "uses_en": ["Pasta puttanesca and piccata", "Smoked salmon and bagels", "Tapenade and dips", "Mediterranean salads", "Fish and chicken dishes"],
            "uses_fr": ["Pâtes puttanesca et piccata", "Saumon fumé et bagels", "Tapenade et trempettes", "Salades méditerranéennes", "Plats de poisson et de poulet"],
            "uses_ar": ["المكرونة والسلمون المدخن", "الكعك", "التغميسات والسلطات", "أطباق الأسماك والدجاج", "أطباق البحر الأبيض المتوسط"],
            "specifications_en": {"Packaging": "Premium glass jar", "Origin": "Morocco", "Grade": "Premium Hand-Picked"},
            "specifications_fr": {"Emballage": "Bocal en verre premium", "Origine": "Maroc", "Qualité": "Premium Cueillies à la Main"},
            "specifications_ar": {"التعبئة": "وعاء زجاجي فاخر", "المنشأ": "المغرب", "الجودة": "منتقى يدويا ممتاز"},
            "is_featured": False
        }
    ]

    for p_data in products_data:
        Product.objects.create(**p_data)
        print(f"Created: {p_data['name_en']}")
        
    print(f"Successfully populated database with {len(products_data)} products.")

if __name__ == '__main__':
    populate()
