# Generated by Django 6.0.5 on 2026-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('wholesale_interest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('vinegars', 'Premium Vinegars'), ('pickles', 'Pickled Vegetables & Condiments'), ('spicy', 'Hot & Spicy')], max_length=100)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('description_ar', models.TextField()),
                ('features_en', models.JSONField(default=list)),
                ('features_fr', models.JSONField(default=list)),
                ('features_ar', models.JSONField(default=list)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CAPERSMED', max_length=200)),
                ('phone', models.CharField(default='+212 6 61 48 28 83', max_length=50)),
                ('email', models.EmailField(default='info@capersmed.com', max_length=254)),
                ('address', models.TextField(default='Hay Namae Bensouda 371/3, Fes 30000, Morocco')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
