# Generated by Django 6.0.5 on 2026-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ar',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fr',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_ar',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_en',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_fr',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='uses_ar',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='uses_en',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='uses_fr',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
