# Generated by Django 4.2.30 on 2026-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_is_premium_product_short_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
