# Generated by Django 6.0.5 on 2026-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_certifications_product_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=250)),
                ('title_fr', models.CharField(blank=True, max_length=250)),
                ('title_ar', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('category', models.CharField(choices=[('news', 'Company News'), ('industry', 'Industry Insights'), ('recipes', 'Recipes & Uses'), ('export', 'Export & Trade'), ('products', 'Product Spotlight')], default='news', max_length=50)),
                ('excerpt_en', models.TextField(blank=True, max_length=400)),
                ('excerpt_fr', models.TextField(blank=True, max_length=400)),
                ('excerpt_ar', models.TextField(blank=True, max_length=400)),
                ('content_en', models.TextField()),
                ('content_fr', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='CAPERSMED Team', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
