# Generated by Django 6.0.5 on 2026-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='🏅', max_length=10)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Packaging',
                'verbose_name_plural': 'Packaging Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Preservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Preservation Method',
                'verbose_name_plural': 'Preservation Methods',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('capers', 'Capers & Caperberries'), ('peppers', 'Peppers & Hot Products'), ('pickles', 'Pickled Vegetables & Condiments')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='product',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
        migrations.AddField(
            model_name='product',
            name='preservation',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.preservation'),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.certification'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.packaging'),
        ),
    ]
