# Generated by Django 6.0.5 on 2026-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certification_packaging_preservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='packaging',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='packaging',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='packaging',
            name='name_it',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preservation',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preservation',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preservation',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preservation',
            name='name_it',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
