# Generated by Django 6.0.5 on 2026-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_packaging_name_ar_packaging_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calibers',
            field=models.JSONField(blank=True, default=list, help_text='Available calibers e.g. [1, 2, 3]'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='features_es',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='features_it',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='grades',
            field=models.JSONField(blank=True, default=list, help_text='Available grades e.g. ["A","B","C","D","E"]'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='name_it',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, default='Morocco', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_es',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_it',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_es',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_it',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='uses_es',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='uses_it',
            field=models.JSONField(default=list),
        ),
    ]
