# Generated by Django 6.0.5 on 2026-05-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_features_ar_alter_product_features_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='capersmed.maroc@gmail.com', max_length=254),
        ),
    ]
