# Generated by Django 6.0.5 on 2026-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_certification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_it',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='subtitle_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='subtitle_es',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='subtitle_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='subtitle_it',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
