# Generated by Django 6.0.5 on 2026-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_certification_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='theme_color',
            field=models.CharField(default='#1B4332', max_length=20),
        ),
    ]
