# Generated by Django 6.0.5 on 2026-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_certification_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_it',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_pt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_es',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_it',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_pt',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_it',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_pt',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_pt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='subtitle_pt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='packaging',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preservation',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='features_pt',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_pt',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_pt',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='uses_pt',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
