# Generated by Django 6.0.5 on 2026-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blogpost_content_es_blogpost_content_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calibre',
            field=models.CharField(blank=True, default=None, help_text='Product calibre e.g. "7/8", "8/9", "9/11", "11/13", "13+"', max_length=100, null=True),
        ),
    ]
