# Generated by Django 6.0.5 on 2026-05-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_calibre_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_it',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_pt',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
    ]
