# Generated by Django 6.0.5 on 2026-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_blogpost_slug_ar_blogpost_slug_es_blogpost_slug_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_it',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_pt',
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_it',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_pt',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
    ]
