# Generated by Django 6.0.5 on 2026-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_blogpost_slug_ar_remove_blogpost_slug_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('about', 'About Us'), ('products', 'Products'), ('certifications', 'Certifications'), ('blog', 'Blog'), ('branding', 'Branding'), ('contact', 'Contact'), ('services', 'Services')], help_text='Which page this hero background is for.', max_length=50, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload a hero background image (JPEG, PNG, WebP).', null=True, upload_to='backgrounds/')),
                ('video', models.FileField(blank=True, help_text='Upload a hero background video (MP4, WebM). Used only when media type is Video.', null=True, upload_to='backgrounds/videos/')),
            ],
            options={
                'verbose_name': 'Hero Background',
                'verbose_name_plural': 'Hero Backgrounds',
                'ordering': ['page'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_it',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_pt',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
    ]
