# Generated by Django 6.0.5 on 2026-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_heromedia_blogpost_slug_ar_blogpost_slug_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='export@capersmed.com', max_length=254),
        ),
    ]
