# Generated by Django 6.0.5 on 2026-05-20 20:58

from django.db import migrations

def update_email(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    for settings in SiteSettings.objects.all():
        if settings.email == 'capersmed.maroc@gmail.com':
            settings.email = 'export@capersmed.com'
            settings.save()

def reverse_update_email(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_sitesettings_email'),
    ]

    operations = [
        migrations.RunPython(update_email, reverse_code=reverse_update_email),
    ]
